### ISSUE TITLE
Package Yunohost

### ISSUE THREAD

**Issue by Krakinou** [kepon85/emailPoubelle.php#1]
Continuation de https://framagit.org/kepon/emailPoubellePhp/issues/10
et https://github.com/matlink/emailpoubelle_ynh/issues/3

Hello David,
Comme je préfère github, j'ai re-ouvert un nouveau message (parce que 3 c'était pas assez :) )
Oui, je suis bien motivé, j'ai toujours eu envie de m'essayer à ce genre de chose. En termes de capacités, j'espère ne pas être plus con qu'un autre...
Mes limites sont plus sur s'il y a des "vrais" développement php à faire ou dans la gestion détaillée des serveurs d'emails, mais pour le packaging, les scripts ou la bidouille technique, ça devrait aller.
Ce que je te propose c'est de forker ton dépot avec la version 2.0 et de le mixer avec les scripts qu'avait déjà construit Matlink et déjà voir ce que cela donne.
Je teste tout ça sur mon yunohost de dev, si ça marche sur celui de prod et je reviens vers toi si j'ai des soucis.
A+
Krakinou

**Comment by kepon85** [comment]
Salut,
Super si tu 'as un problème n'hésite pas ! 
Je te suggère d'utiliser la base sqlite plutôt que mysql (comme l'avait fait et matlink) ça simplifie le script d'installation...
David

**Comment by Krakinou** [comment]
Hello David,
J'ai une première question : lorsque je tente d'installer la version 2.0 d'emailpoubelle sur mon yunohost et que je la lance, j'ai le message suivant qui s'affiche:
`setlocale failed: locale function is not available on this platform, or the given local does not exist in this environment`

J'ai donc creuser un peu et j'ai remarqué que si dans ep_header.php, j'insère 
`$lang='fr_FR';`
avant la définition de la langue, alors emailPoubelle s'affiche correctement.
Si je renseigne une autre langue (it_IT, en_US, en_GB...) cela ne fonctionne pas.

Mes locales:
```
root@yuno:/var/www/emailpoubelle/lib # locale -a
C
C.UTF-8
fr_FR.utf8
POSIX
root@YunoHost:~ # locale
LANG=fr_FR.UTF-8
LANGUAGE=
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=

```
J'ai également tenté un 
```
root@yuno:/var/www/emailpoubelle/lib # sudo apt install locales-all && sudo dpkg --configure -a
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Les NOUVEAUX paquets suivants seront installés :
  locales-all
0 mis à jour, 1 nouvellement installés, 0 à enlever et 0 non mis à jour.
Il est nécessaire de prendre 3 624 ko dans les archives.
Après cette opération, 130 Mo d'espace disque supplémentaires seront utilisés.
Réception de:1 http://ftp.debian.org/debian stretch/main amd64 locales-all amd64 2.24-11+deb9u3 [3 624 kB]
3 624 ko réceptionnés en 4s (747 ko/s)   
Sélection du paquet locales-all précédemment désélectionné.
(Lecture de la base de données... 53857 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../locales-all_2.24-11+deb9u3_amd64.deb ...
Dépaquetage de locales-all (2.24-11+deb9u3) ...
Paramétrage de locales-all (2.24-11+deb9u3) ...
root@yuno:/var/www/emailpoubelle/lib # locale -a
aa_DJ
aa_DJ.utf8
aa_ER
aa_ER@saaho
aa_ET
af_ZA
af_ZA.utf8
ak_GH
am_ET
an_ES
an_ES.utf8
anp_IN
ar_AE
ar_AE.utf8
ar_BH
ar_BH.utf8
ar_DZ
ar_DZ.utf8
ar_EG
ar_EG.utf8
ar_IN
ar_IQ
ar_IQ.utf8
ar_JO
ar_JO.utf8
ar_KW
ar_KW.utf8
ar_LB
ar_LB.utf8
ar_LY
ar_LY.utf8
ar_MA
ar_MA.utf8
ar_OM
ar_OM.utf8
ar_QA
ar_QA.utf8
ar_SA
ar_SA.utf8
ar_SD
ar_SD.utf8
ar_SS
ar_SY
ar_SY.utf8
ar_TN
ar_TN.utf8
ar_YE
ar_YE.utf8
as_IN
ast_ES
ast_ES.utf8
ayc_PE
az_AZ
be_BY
be_BY@latin
be_BY.utf8
bem_ZM
ber_DZ
ber_MA
bg_BG
bg_BG.utf8
bhb_IN.utf8
bho_IN
bn_BD
bn_IN
bo_CN
bo_IN
br_FR
br_FR@euro
br_FR.utf8
brx_IN
bs_BA
bs_BA.utf8
byn_ER
C
ca_AD
ca_AD.utf8
ca_ES
ca_ES@euro
ca_ES.utf8
ca_ES.utf8@valencia
ca_ES@valencia
ca_FR
ca_FR.utf8
ca_IT
ca_IT.utf8
ce_RU
chr_US
cmn_TW
crh_UA
csb_PL
cs_CZ
cs_CZ.utf8
C.UTF-8
cv_RU
cy_GB
cy_GB.utf8
...
```
qui m'a installé toutes les locales possibles et imaginables, mais pas mieux.
Aurais-tu une idée?

**Comment by Krakinou** [comment]
Gagné!
Un` systemctl restart php7.0-fpm` suivi d'un `systemctl restart nginx` ont bien résolu le pb!
Pour moi aussi, ça reste quelque chose de très obscur...
Merci en tout cas!

**Comment by Krakinou** [comment]
Pour info
https://forum.yunohost.org/t/emailpoubelle-2-0-manage-email-aliases/6339

**Comment by kepon85** [comment]
Super boulot !
Merci pour ta contribution !!!
